events {}

http {
    server {
        listen 80;

        client_max_body_size 10m;

        location /images/ {
            alias /images/;
        }

        location / {
            proxy_pass http://app:8000;
        }
    }
}